### ISSUE TITLE
Consider generating code from API definition

### ISSUE THREAD

**Issue by nstogner** [moov-io/paygate#1]
I have found it nice to generate code from API definitions (as opposed to the opposite direction). It looks like you might be manually writing each here right now? I would take a good look at generating from protobufs... It is a very nice way of defining services. You get benefits of gRPC + the swagger/REST stuff for free (for clients who like REST).

If you havent already looked into Google's API design docs, I think they are top-notch: https://cloud.google.com/apis/design/

Just some ideas...

**Comment by wadearnold** [comment]
That's definitly the goal based on the api specification
https://github.com/moov-io/achsvc/blob/master/api/openapi.yaml

I should probably write the code in my own repo as I try an figure out the best way to architect the solution.

**Comment by nstogner** [comment]
Saw that you had that there... I tend to favor `.proto` files as the master IDL (the origination of the generation) as you can generate those pesky swagger files off of them as well. The `protoc` tool also makes it easy to extend generation for your domain needs.

**Comment by adamdecaf** [comment]
I think we'd generate clients (probably just in Go) off the swagger file(s) and help out others to generate clients in other languages.

I'm thinking we should have one swagger / api reference. https://github.com/moov-io/docs/issues/5

**Comment by adamdecaf** [comment]
We're doing this over at https://github.com/moov-io/go-client (we will automate building this).

Our OpenAPI spec lives here: https://github.com/moov-io/api/blob/master/openapi.yaml
