### ISSUE TITLE
HTTP endpoints for file-transfer configs

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#147]
We should expose HTTP endpoints for SFTP, cutoff times, and ACH file transfers (uploads). This allows back office tools to inspect and modify them. 

First, let's create a read endpoint that masks any passwords. If there are requests for more let's add those.

**Comment by tgunnoe** [comment]
Why not use local config envs or the config file idea? I believe this would be better for one time setup items, like how the environment variables work. It would seems to be an easier implementation in any case.

**Comment by adamdecaf** [comment]
It would be tricky to configure paygate using env variables when multiple routing numbers are configured. We would need to embed the routing number in each env var or some similar scheme. (i.e. `XX_SFTP_USERNAME`)

We could support reading these configs from a file.

**Comment by wadearnold** [comment]
Admin Paths for all environment variables are key to automation. As a user I want the system to come up in my environment variable state but would like to update the state of the running application. I think Kubernetes does a good job of supporting both.
