### ISSUE TITLE
X-Idempotency-Key support

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#15]
> Idempotent key in the header which expires after 24 hours. These strings should contain enough entropy for to not collide with each other in your requests.

We need to support this somehow. Redis?

**Comment by wadearnold** [comment]
This is an important issue for /transfers/ I picked 24hrs because that is what stripe was using. Really we just need a couple minutes at most. The API should be able to double check that it was a duplicate transaction if the system is in sync.

**Comment by wadearnold** [comment]
I agree on deferring for the Redis dependency. Maybe we should just make that it's own issue for some other day.
