### ISSUE TITLE
transfers: YYYDetail (i.e. WEBDetail) sub-objects are often copied incorrectly

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/paygate#164]
```
jq -n --arg orig $ORIGINATOR_ID --arg origDep $DEPOSIT_ID1 --arg rec $RECEIVER_ID --arg recDep $DEPOSIT_ID2 '{"transferType": "push", "amount": "USD 99.99", "originator": $orig, "originatorDepository": $origDep, "receiver": $rec, "receiverDepository": $recDep, "description": "Loan Pay", "standardEntryClassCode": "WEB", "sameDay": false, "CCDDetail": { "paymentInformation": "test payment" }, "WEBDetail": { "paymentInformation": "test payment", "paymentType": "single" } }' | curl -k -o - -s  --header "X-User-Id: $USER_ID" --request POST --url https://moov-paygate.$SANDBOX/transfers --data @- | jq .
{
  "error": "createACHFile: WEB: createWEBBatch: reoccurring WEB transfers are not supported yet"
}
```

In the detail above the WEB type is "single".  However, I get an error saying reoccurring WEB transfers are not support.

Are any WEB type transfers supported yet?

**Comment by adamdecaf** [comment]
That is strange.. I took your JSON and verified the WEBDetail.PaymentType is `single`, so I'm not sure how that error is generated. 

`createWEBBatch: reoccurring WEB transfers are not supported` is generated with the incoming paymentType, so it looks like the JSON had `reoccurring`. 

In my tests I kept in the `CCDDetail` sub-object, but that's not read for WEB transfers.

**Comment by adamdecaf** [comment]
This is what I was using to double check the JSON body: 

```go
func TestWEBTransfer__json(t *testing.T) {
	body := strings.NewReader(`{
"transferType": "push",
"amount": "USD 99.99",
"originator": "$orig",
"originatorDepository": "$origDep",
"receiver": "$rec",
"receiverDepository": "$recDep",
"description": "Loan Pay",
"standardEntryClassCode": "WEB",
"sameDay": false,
"CCDDetail": { "paymentInformation": "test payment" },
"WEBDetail": { "paymentInformation": "test payment", "paymentType": "single" }
}`)
	var req transferRequest
	if err := json.NewDecoder(body).Decode(&req); err != nil {
		t.Fatal(err)
	}

	t.Errorf("%#v", req)
	t.Errorf("%#v", req.WEBDetail)
	t.Error(req.WEBDetail.PaymentType == WEBSingle)
}
```

**Comment by rayjlinden** [comment]
I'm not 100% on this because I have not had time to adding debugging statements.  However, I think the problem might be here:
			transfer := req.asTransfer(id)

The asTransfer method does not appear to copy over the WEB, TEL or any other substructure.  So the values would all be nil.  This would trigger the error I see.

**Comment by adamdecaf** [comment]
I started a build (v0.6.0-rc1) with this fix added - https://travis-ci.com/moov-io/paygate/builds/118348590
