### ISSUE TITLE
WIP - Account Validation 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/paygate#169]
Account validation is an important tool for businesses who originate ACH credits and debits. Using an incorrect routing and transit number and/or account number for the recipient of an ACH transaction can cost a business both time and money. It can damage a company’s relationship with employees, customers and vendors; result in fees from a company’s financial institution; delay the start of an employee’s direct deposit of payroll; cause payments to suppliers to fail, and delay in the collection of funds from customers. Using account validation enables businesses to reduce returned transactions, in cases where an account number was incorrectly entered, and fraudulent payments, where the wrong account number was purposefully entered. It also helps to provide a positive customer experience while reducing the number of customer service calls and lost customers.

- Micro-Deposits Through ACH
A company sends one or two very small credit ACH transactions (and sometimes a debit to remove the money) to their customer. The customer informs the company what amount(s) were deposited to and debited from their account. This verifies the account number and ensures the customer has the ability to view the account.

- ACH Validation Test
The ACH Network connects to all financial institutions across the U.S. Companies can send a prenote through the ACH Network to their customer’s bank and verify the accuracy of bank account information.

- Manual Methods
A company uses consumer’s check to verify account information and uses identification to confirm consumer identity, and/or company calls the consumer’s financial institution.

- Validation Services
Some financial institutions and third parties have access to a large number of accounts (both their own and others) and may offer a product that leverages this information. A company can access these services for scoring as to the likelihood of correct account information and/or the account holder’s identity. These responses can be real-time, same-day or next-day and can do many things besides validating the account number and ownership, including the provision of information on the account itself (age, returns, etc.).

- Account Aggregation
Companies such as [Plaid](https://plaid.com/products/auth/) and [MX](https://data.mx.com/products/instant-verification) offer account aggregation services that allow the consumer to login to their bank account and return a routing number, account number, account holder, and available balance to be used for approving the account information. 

## Updated WEB Account Validation requirements March 19, 2021

Currently, ACH Originators of WEB debit entries are required to use a “commercially reasonable fraudulent transaction detection system” to screen WEB debits for fraud. This existing screening requirement will be supplemented to make it explicit that “account validation” is part of a “commercially reasonable fraudulent transaction detection system.” The supplemental requirement applies to the first use of an account number, or changes to the account number.

*The WEB Debit Account Validation Rule now takes effect March 19, 2021, rather than Jan. 1, 2020*

[Supplementing Fraud Detection Standards for WEB Debits](https://www.nacha.org/rules/supplementing-fraud-detection-standards-web-debits)

Credit NACHA [Account Verification Overview PDF](https://www.nacha.org/system/files/resources/Nacha_AcctValidation_WP_FINAL.pdf)

## PayGate support for Account Validation 

Documentation, examples, and use cases should be created for each of the Account Validation types. These should be sub-issues of this task.

**Comment by adamdecaf** [comment]
We've solved a lot of this already (micro-deposits) and most of the work will occur in Customers.
