### ISSUE TITLE
protocol for writing to bank server

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/paygate#170]
Currently, paygate just supports ftp to write to the bank.  This is not very secure and I doubt many banks still support it.  One could add TLS to the current implementation to support FTPS.  Our bank requires SFTP (which is really more ssh).  In Go - this will require a different implementation.  I've seen this package used in a couple of projects to support SFTP: https://github.com/pkg/sftp

I know our bank will require SFTP.  (No idea how many banks may use FTPS.  My understanding is SFTP is generally more secure - but that doesn't mean much if your bank requires something specific.  :)

I was going to take a stab at implementing SFTP support for paygate.  It would mostly mean replacing  the file file_transfer.go.

However, I'm wondering if/how you would want configuration of choosing SFTP vs. FTP vs FTPS to work.

**Comment by adamdecaf** [comment]
Yes. It's my bad to call the FTP implementation SFTP. I mean FTP(s) where both FTP and FTP+TLS are supported. I had planned on support other transport protocols.

**Comment by adamdecaf** [comment]
SFTP support has been merged and FTP supports TLS via `ACH_FILE_TRANSFERS_CAFILE`. Both will be released in v0.6.0 (and in a release candidate).
