### ISSUE TITLE
How does the status change for a customer, depository, and transfer ? 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#18]
Right now the `Customer`, `Depository` and `Transfer` have their own status enums, but there's no support in the API for updating the status. I'm assuming transfers can only happen if all the components are verified. 

Does this need to be part of existing endpoints? Admin backend to approve?

**Comment by wadearnold** [comment]
- There is an OAuth application user that registers at signup. 
- The OAuth application is the Originator. Most use cases will have a single Originator record. 
- The Originator MUST have a Depository to be able to have a transfer 
- The Originator MAY have more than one Depository (probably at the same bank)
- A Depository needs to be validated. Probably by admin or two matching deposits. Maybe the bank pre-approves Depository's if they are at the bank. 
- A Customer can handle Credits (push) or Debits (pull) or Both (credit, debit)
- A Customer has a Depository. There are additional checks that need to be done for Pull (debit) than Push (credit). Most people like getting money but need to authorize it being pulled. 
- Again a Depository may be validated by the admin, two deposits, Plaid, etc. 

I think validating a Depository via the admin api would have a reason. A Plaid or Dual Deposits would be an auto approval for that status change. 

Not really for this thread. We should probably rename Customer to Receiver. But that's it's own thing.

**Comment by adamdecaf** [comment]
> A Customer has a Depository. There are additional checks that need to be done for Pull (debit) than Push (credit). Most people like getting money but need to authorize it being pulled.

Ah. The Customer has extra checks and could be Verified before it's Depository then? The Customer has a status field now (and the Depository has its own).
