### ISSUE TITLE
In api/openapi.yaml, consider changing tag name Customers to Receivers

### ISSUE THREAD

**Issue by chuckiebluestar** [moov-io/paygate#2]
The term 'receiver' is more correct for indicating the other side of a transfer from an Originator.

**Comment by adamdecaf** [comment]
cc @wadearnold

**Comment by adamdecaf** [comment]
We're doing this over at https://github.com/moov-io/go-client (we will automate building this).

Our OpenAPI spec lives here: https://github.com/moov-io/api/blob/master/openapi.yaml
