### ISSUE TITLE
could use sync version of the flush endpoints

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/paygate#276]
The current admin endpoints to flush incoming or outgoing ach files are asynchronous.  There are use cases where this is exactly what you would want - so I do not want to change it.

However, there are use cases - like testing where it would be very helpful it the calls were synchronous.  Currently, in our test scripts we need to wait two or three seconds after doing a flush before checking the results of the processing.  This adds unneeded time to tests (or if you don't sleep long enough) brittle tests.

I'd like to request an option on those urls (maybe via a query string?) that would do the processing synchronously and return when processing is done.  This would make testing a little easier.

**Comment by adamdecaf** [comment]
@rayjlinden good call. I created https://github.com/moov-io/paygate/pull/278 with `?wait` for this.
