### ISSUE TITLE
ACH file values for POST /transfers

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#29]
Part of https://github.com/moov-io/paygate/issues/8 is to actually create the ACH files and send them over to our ACH service. To do this we need to figure out the specific values.

For a transfer, are we just supporting Push for now? Wade has [mentioned Pull is more complicated](https://github.com/moov-io/paygate/issues/18#issuecomment-432066045).

Here's the values I want to confirm:

https://github.com/adamdecaf/paygate/blob/create-ach-file/transfers.go#L686

**Batch**
- `ServiceClassCode`: Credits 220 / Debits 225 (Push would be Credit?)
- `StandardEntryClassCode`: I defaulted to `PPD` just to get something working
- `CompanyIdentification`: 9 digit FEIN number 
- `EffectiveEntryDate`: End of Day today? Tomorrow? 

**EntryDetails**
- `TransactionCode`:  22 / 23 / 27 / 28 / 32 / 33 / 37 / 38
   - I think this can be handled by a fancy switch, Push is Credit?
- `IdentificationNumber`: Do we have API support to capture this? 
- `TraceNumber`: How do we want to manage/generate this?

**Comment by adamdecaf** [comment]
For reference here's a JSON document paygate generated. 

```json
{
    "fileControl": {
        "entryAddendaCount": 0,
        "blockCount": 1,
        "batchCount": 1,
        "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
    },
    "IATBatches": null,
    "batches": [
        {
            "batchControl": {
                "entryHash": 23138010,
                "batchNumber": 1,
                "ODFIIdentification": "12104288",
                "companyIdentification": "121042882",
                "entryAddendaÇount": 0,
                "serviceClassCode": 200,
                "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
            },
            "entryDetails": [
                {
                    "category": "Forward",
                    "traceNumber": 121042880000001,
                    "discretionaryData": "test payment",
                    "individualName": "",
                    "identificationNumber": "#83738AB#      ",
                    "amount": 7854,
                    "DFIAccountNumber": "451",
                    "checkDigit": "4",
                    "RDFIIdentification": "23138010",
                    "transactionCode": 22,
                    "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
                }
            ],
            "batchHeader": {
                "batchNumber": 1,
                "ODFIIdentification": "12104288",
                "effectiveEntryDate": "2018-10-30T18:01:42.535676-07:00",
                "companyEntryDescription": "test payment",
                "standardEntryClassCode": "PPD",
                "companyIdentification": "121042882",
                "companyName": "",
                "serviceClassCode": 200,
                "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
            }
        }
    ],
    "fileHeader": {
        "fileIDModifier": "A",
        "fileCreationTime": "2018-10-30T18:01:42.535686-07:00",
        "fileCreationDate": "2018-10-30T18:01:42.535686-07:00",
        "immediateDestinationName": "cust bank",
        "immediateDestination": "231380104",
        "immediateOriginName": "orig bank",
        "immediateOrigin": "121042882",
        "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
    },
    "id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
}
```

**Comment by adamdecaf** [comment]
cc @bkmoovio

**Comment by bkmoovio** [comment]
This looks to be what you are trying to do:

1)	Create an ACH file containing WEB entries from JSON using moov-io/ach library
•	Create a File Header:
The following properties have default settings and don’t need to be passed in.
// NewFileHeader returns a new FileHeader with default values for none exported fields
func NewFileHeader() FileHeader {
   fh := FileHeader{
      recordType:     "1",
      priorityCode:   "01",
      FileIDModifier: "A",
      recordSize:     "094",
      blockingFactor: "10",
      formatCode:     "1",
   }
   return fh
}

2)	Create a batch of WEB entries
•	Create a WEB Batch Header
•	Create WEB Entry Detail
•	Create Addenda05

**Comment by bkmoovio** [comment]
{
	"fileHeader": {
		"fileCreationTime": "2018-10-30T18:01:42.535686-07:00",
		"fileCreationDate": "2018-10-30T18:01:42.535686-07:00",
		"immediateDestinationName": "Citadel",
		"immediateDestination": "231380104",
		"immediateOriginName": "Wells Fargo",
		"immediateOrigin": "121042882",
		"id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573a"
	},
	"batches": [
		"batchHeader", {
			"serviceClassCode": "220",
			"companyName": "Name on Account",
			"companyIdentification": "121042882",
			"standardEntryClassCode": "WEB",
			"companyEntryDescription": "Subscribe",
			"effectiveEntryDate": "2018-10-30T18:01:42.535686-07:00",
			"ODFIIdentification": "12104288",
			"id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573b"
		}
	],
	"entryDetails": [
		"entry", {
			"category": "Forward",
			"transactionCode": "22",
			"RDFIIdentification": "231380104",
			"DFIAccountNumber": "12345678",
			"amount": "01",
			"individualname": "Wade Arnold",
			"traceNumber": " 121042880000001",
			"identificationNumber": "#789654",
			"discretionaryData": "S",
			"Addenda": {
				"typeCode": "05",
				"paymentRelatedInformation": "PAY-GATE Payment",
				"id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573d"
			},
			"id": "5a4df13f8f2cb381e621aab6a3f736f9d9dd573c"
		}
	]
}
