### ISSUE TITLE
Return json body with readable message on getting NACHA return code instead of returning only Http status code

### ISSUE THREAD

**Issue by chanhengseang3** [moov-io/paygate#426]
![image](https://user-images.githubusercontent.com/26960131/76733379-47c27080-6793-11ea-89d7-0dc59a76a5cc.png)

Imagine there is error regarding to receiver account is closed, what message is the best for users.

**Comment by adamdecaf** [comment]
@chanhengseang3 This was documented wrong. In the "200 OK" state PayGate returns `[]ach.File` where the `ach.ReturnCode` objects are populated: https://godoc.org/github.com/moov-io/ach#File.ReturnEntries

**Comment by adamdecaf** [comment]
@chanhengseang3 

Are you using `github.com/moov-io/paygate/client`? Running `go get github.com/moov-io/paygate/client@master` would pull in this change.

I can update `github.com/moov-io/go-client/client` with these changes if needed.

**Comment by chanhengseang3** [comment]
@adamdecaf  ok, thanks.

**Comment by adamdecaf** [comment]
@chanhengseang3 Did you need go-client updated?
