### ISSUE TITLE
ach: store IdentificationNumber for each file?

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#467]
On each `EntryDetail` we create a random ID that's set, but we don't store this. `TraceNumber` is typically used to re-identify an Entry, but I think we could use IdentificationNumber also (or hash it). 

```go
entryDetail.IdentificationNumber = createIdentificationNumber()
```

The ACH docs: 
```go
// IdentificationNumber an internal identification (alphanumeric) that
// you use to uniquely identify this Entry Detail Record
IdentificationNumber string `json:"identificationNumber,omitempty"`
```

**Comment by wadearnold** [comment]
Appendix Four: Return Entries 

_When a Return Entry is prepared, the original Company/Batch Header Record, the original Entry Detail Record, and the Company/Batch Control Record are copied for return to the Originator._

Should we store this data for easy lookup or even make it a hash? We would also want to know the file that was used to submit the transfer. 
<img width="775" alt="Screen Shot 2020-04-06 at 12 59 00 PM" src="https://user-images.githubusercontent.com/32989/78594981-6fdb4780-7806-11ea-9c42-89253d0e8489.png">

**Comment by adamdecaf** [comment]
We're good with storing just trace number for now.
