### ISSUE TITLE
Setup/Install Issues

### ISSUE THREAD

**Issue by wad0687** [moov-io/paygate#488]
I feel like we are doing something wrong that is simple, but can't figure it out. We have a fresh Debian Install. Have installed docker/docker-compose and followed the instructions online to pull down paygate, then we do docker-compose up -d, all of the services come up with no errors, but paygate doesn't seem to be able to work properly. Before we can even continue onto the next steps the simple test of http://localhost:8082/ping gives a 404 page not found response, same with accessing on port 8082 all together, but seems to work fine on the other ports that were defined.

**Comment by adamdecaf** [comment]
Hey @wad0687,

Are you running PayGate from the master branch? If so can you try [`release-v0.7`](https://github.com/moov-io/paygate/tree/release-v0.7). We've got a lot of changes on `master` and it's not quite ready for prime time yet.

**Comment by adamdecaf** [comment]
@wad0687 have you been able to get PayGate running?

**Comment by wad0687** [comment]
Sorry, this was resolved by using the older branch as mentioned.

ALAN DRURY
DevOps Engineer

[image: IQventures logo]
614.379.6526 *office*
iqventures.com <http://www.iqventures.com/> | speechiq.com
<http://www.speechiq.com/> | businessphone.com
<http://www.businessphone.com/>

**Comment by adamdecaf** [comment]
Sounds good! Let us know if you have any issues.
