### ISSUE TITLE
proposal: Tie ACH and OFAC boot checks to admin servlet status code

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#50]
Rather than calling `panic` on startup if our dependencies aren't healthy we should have the admin servlet be unhealthy. That way a dependency can be down and paygate launches.

**Comment by wadearnold** [comment]
I was thinking the admin servlet was a hard dependency; hence the panic.

**Comment by adamdecaf** [comment]
(Forgot to link the code before) - https://github.com/moov-io/paygate/blob/v0.2.1/main.go#L93 

Kubernets can hold off letting that pod be ready (and get traffic) by checking the admin servlet. Right now the admin servlet isn't aware of the ach dependency though.

**Comment by adamdecaf** [comment]
FYI, let's look at using https://github.com/heptiolabs/healthcheck for this
