### ISSUE TITLE
amount: break apart into object 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#569]
PayGate Version: `v0.9.0-dev`

@joshsadler brought up that developers using PayGate would have an easier time by not needing to concat/parse our amount modeling. (`USD 12.04`) This is cumbersome and requires callers to understand that logic. 

Instead a model like this would be easier to use. 
```json
{
  "amount": {
    "value": 1204,
    "currency": "USD"
  }
}
```

**Comment by joshsadler** [comment]
@adamdecaf this is much easier to use. Any particular reason to favor a string for value rather than a number?

**Comment by adamdecaf** [comment]
Floating point can mess with amounts and cause off-by-$0.01 errors. Various programming languages treat floats differently and JS is especially bad about it. 

Internally we compute amounts as ints and in their value in cents. No floating point is used internally. 

https://modernweb.com/what-every-javascript-developer-should-know-about-floating-points/

**Comment by wadearnold** [comment]
Another option is to use plain integers to represent a currency. If you make $1.01 into 101¢ and perform all your calculations on cent integers you will never run into these floating-point approximation issues, as you are no longer performing approximations. 

From Stripe: 
_All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge 10 USD, provide an amount value of 1000 (i.e., 1000 cents).

For zero-decimal currencies, still provide amounts as an integer but without multiplying by 100. For example, to charge ¥500, provide an amount value of 500._



Stripe golang SDK uses int64
https://github.com/stripe/stripe-go/blob/master/balance.go#L23

Interesting how go-money creates a similar structure in int64
https://github.com/Rhymond/go-money/blob/master/money.go#L42

**Comment by joshsadler** [comment]
Given the prior art @wadearnold posted, that sounds like a solid approach. Looks to be safely handle-able in many programming languages. I'm on board 👍

**Comment by adamdecaf** [comment]
We can expose `value` as an integer - internally our `Amount` type has always computed off integers. We are [splitting at the decimal](https://github.com/moov-io/paygate/blob/v0.8.0/pkg/model/amount.go#L137) to avoid floating point errors.
