### ISSUE TITLE
CustomerIDs query param not being honored

### ISSUE THREAD

**Issue by joshsadler** [moov-io/paygate#582]
According to the API docs (https://api.moov.io/v1/#operation/getTransfers) the `GET /transfers` endpoint should accept an optional query param for `customerIDs` which would limit the results of the request to any transfer where that customerID was in the source or destination.

This is not functioning as expected today. The result is not filtered.

**Comment by adamdecaf** [comment]
This would match as `source_customer_id = ? or destination_customer_id = ?` [from our database](https://github.com/moov-io/paygate/blob/b9a76075c615552896e05b4fec4d4b5aab19fc83/pkg/database/mysql.go). 

We currently aren't reading this query param: https://github.com/moov-io/paygate/blob/b9a76075c615552896e05b4fec4d4b5aab19fc83/pkg/transfers/router.go#L87

**Comment by vxio** [comment]
I can patch this.
