### ISSUE TITLE
Transfer status query param not working as expected

### ISSUE THREAD

**Issue by joshsadler** [moov-io/paygate#583]
When filtering transfers by status, you construct a URL such as `GET /api/transfers?limit=50&offset=0&status=failed`

Without a `status` param, the list contains transfers. With the `status` param, the list is empty, even when there are transfers with that status.

**Comment by adamdecaf** [comment]
Weird. We're reading that query param, but I guess not including that into the query. 

We currently aren't reading this query param: https://github.com/moov-io/paygate/blob/b9a76075c615552896e05b4fec4d4b5aab19fc83/pkg/transfers/router.go#L87-L93

**Comment by vxio** [comment]
I'll work on this.
