### ISSUE TITLE
config to enable ACH file batch merging based on the batch header

### ISSUE THREAD

**Issue by theFong** [moov-io/paygate#638]
**What were you trying to do?**
Currently there is no way to configure merging of entry records under the same batch if the batch headers are the same.

**What did you expect to see?**
A configuration option to merge batches if the batch headers are the same.

**Comment by adamdecaf** [comment]
We can do this. When testing out that linked PR I ran into https://github.com/moov-io/ach/issues/863 and https://github.com/moov-io/ach/issues/867 which caused files to not be uploaded. https://github.com/moov-io/ach/issues/866 might be a fix we implement as well.
