### ISSUE TITLE
Refactor Customer to Receiver

### ISSUE THREAD

**Issue by wadearnold** [moov-io/paygate#97]
The codebase and API utilize the ACH term Originator for the company or individual that are generating the credit/debit transaction against a "Customer". Using ACH terminology the "Customer" should be called a "Receiver" throughout the code base and API. 

The background is that "Originator" was previously labelled "Account" which had little to no meaning besides an Account had Customers. An Originator has a Receiver.

**Comment by adamdecaf** [comment]
I've got this setup after the file transfer branches: https://github.com/adamdecaf/paygate/compare/file-transfer-controller...adamdecaf:rename-customer-to-receiver?expand=1

**Comment by wadearnold** [comment]
We will need to update the OpenAPI specification as well 

https://api.moov.io/#tag/Customers

**Comment by adamdecaf** [comment]
Done! https://api.moov.io/#tag/Receivers
